#!/bin/bash
############################################
# mosaic_generic.sh — Siril 马赛克通用拼接脚本
# 依赖 : Siril >= 1.4.0 (siril-cli)
# 输入 : 同一目标、已校准/已堆栈的 FITS panel，放在 staging 目录
# 用法 : ./mosaic_generic.sh <staging_dir> <process_dir> <outputs_dir> [feather_px] [preview_bg]
# 示例 : ./mosaic_generic.sh ./staging ./process ./outputs 128 0.2
# 说明 : SSF 不支持变量，本脚本按官方 bash 教程模式动态生成 mosaic.ssf
#        并落盘到 outputs 目录（可审计、可复跑），再交给 siril-cli 执行
############################################
set -euo pipefail

if [ $# -lt 3 ]; then
    grep '^#' "$0" | cut -c 3-
    exit 1
fi

STAGING=$1
PROCESS=${2:-}
OUTPUTS=${3:-}
FEATHER=${4:-128}
BG=${5:-0.2}

[[ "$FEATHER" =~ ^[0-9]+$ ]] || { echo "feather must be an integer (px)" >&2; exit 1; }
[[ "$BG" =~ ^[0-9]+\.?[0-9]*$ ]] || { echo "preview_bg must be a number (0.05-0.5)" >&2; exit 1; }

# --- 定位 siril-cli: $SIRIL_CLI > PATH > macOS 应用包 ---
SIRIL=${SIRIL_CLI:-}
if [ -z "$SIRIL" ]; then
    SIRIL=$(command -v siril-cli 2>/dev/null || true)
fi
if [ -z "$SIRIL" ] && [ -x /Applications/Siril.app/Contents/MacOS/siril-cli ]; then
    SIRIL=/Applications/Siril.app/Contents/MacOS/siril-cli
fi
[ -n "$SIRIL" ] || { echo "siril-cli not found; install Siril 1.4+ or set SIRIL_CLI" >&2; exit 1; }

# --- 校验输入 ---
[ -d "$STAGING" ] || { echo "staging dir not found: $STAGING" >&2; exit 1; }
STAGING=$(cd "$STAGING" && pwd)
if ! compgen -G "$STAGING/*.fit" >/dev/null \
    && ! compgen -G "$STAGING/*.fits" >/dev/null \
    && ! compgen -G "$STAGING/*.fts" >/dev/null; then
    echo "no FITS panels in $STAGING" >&2
    exit 1
fi

mkdir -p "$PROCESS" "$OUTPUTS"
PROCESS=$(cd "$PROCESS" && pwd)
OUTPUTS=$(cd "$OUTPUTS" && pwd)

# --- 生成 SSF（路径全部参数化）---
SSF="$OUTPUTS/mosaic.ssf"
cat > "$SSF" <<EOF
# generated by mosaic_generic.sh
requires 1.4.0
setext fit
set32bits
cd "$STAGING"
link mosaic "-out=$PROCESS"
cd "$PROCESS"
seqplatesolve mosaic -order=3 -force -nocache
seqapplyreg mosaic -framing=max -interp=la
stack r_mosaic rej none -norm=addscale -overlap_norm -feather=$FEATHER -maximize -32b "-out=$OUTPUTS/mosaic_linear"
load "$OUTPUTS/mosaic_linear.fit"
autostretch -linked -2.8 $BG
savejpg "$OUTPUTS/mosaic_preview" 95
close
EOF

# --- 执行 ---
"$SIRIL" --directory "$STAGING" --script "$SSF"

echo "linear  : $OUTPUTS/mosaic_linear.fit"
echo "preview : $OUTPUTS/mosaic_preview.jpg"
echo "script  : $SSF"
